// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9DK2cf1ZpOTxm1xzqJpQIwLHmTdcMWEY',
    appId: '1:979373514059:web:7fbe3e15b818e069a19cce',
    messagingSenderId: '979373514059',
    projectId: 'stadiksu-2024',
    authDomain: 'stadiksu-2024.firebaseapp.com',
    storageBucket: 'stadiksu-2024.appspot.com',
    measurementId: 'G-758R02MQQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIduFZ8VYBURnsgbTq6VjbougKSrGDn4o',
    appId: '1:979373514059:android:fb6efcdd6eade9a2a19cce',
    messagingSenderId: '979373514059',
    projectId: 'stadiksu-2024',
    storageBucket: 'stadiksu-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKHgwrbN8qDJmtEqTDfMZhRooKfO0KTM',
    appId: '1:979373514059:ios:0b47bb46deef48ada19cce',
    messagingSenderId: '979373514059',
    projectId: 'stadiksu-2024',
    storageBucket: 'stadiksu-2024.appspot.com',
    iosBundleId: 'com.mycompany.satdiksu',
  );
}
